### ISSUE TITLE
doesn't scrape company details anymore

### ISSUE THREAD

**Issue by bricemaurin** [yatish27/linkedin-scraper#81] opened 2016-05-01 18:21 UTC
The company details are not returned anymore for me. Same for you ?

```
profile = Linkedin::Profile.get_profile("http://www.linkedin.com/in/jeffweiner08")
website = profile.current_companies.first[:website]
# nil
```

**Comment by yatish27** [comment] 2016-05-01 18:48
This si a issue. Can you check with proxy ?

**Comment by bricemaurin** [comment] 2016-05-02 08:06
I just tested with a (public) proxy, the profile is returned, not the company page (login page intead)

**Comment by haerde** [comment] 2016-05-06 21:24
@bricemaurin isn't is called `linkedin_company_url`? I'm using [my version of this gem](https://github.com/haerde/linkedin-scraper) and `profile.current_companies.first` returns:
```
{:title=>"CEO", :company=>"LinkedIn", :company_logo=>"https://media.licdn.com/media/AAEAAQAAAAAAAAL0AAAAJGMwYWZhNTYxLWJkMTktNDAzMi05NzEzLTlhNzUxMGU0NDg0Mw.png", :duration=>"7 years 6 months", :start_date=>Mon, 01 Dec 2008, :end_date=>"Present", :linkedin_company_url=>"https://www.linkedin.com/company/linkedin?trk=ppro_cprof"}
```

**Comment by yatish27** [comment] 2016-05-06 22:10
But if you look at the readme it has many more keys. It seems to stop working. Looking into it

**Comment by yatish27** [comment] 2016-05-10 01:21
The issue is fixed in master now. Will be releasing the gem 2.0 later tomorrow @bricemaurin

**Closed by yatish27** 2016-05-10 01:21 UTC

**Comment by bricemaurin** [comment] 2016-05-10 07:46
Thanks Yatish, what's the commit that fixed it ? I'd like to have a look at the code to understand the issue.

**Comment by yatish27** [comment] 2016-05-10 16:37
```
def get_company_details(link)
      sleep(1.5)
      parsed = URI::parse(get_linkedin_company_url(link))
      parsed.fragment = parsed.query = nil
      result = { linkedin_company_url: parsed.to_s }

      page = http_client.get(parsed.to_s)
      company_details = JSON.parse(page.at('#stream-footer-embed-id-content').children.first.text) rescue nil
      if company_details
        result[:website] = company_details['website']
        result[:description] = company_details['description']
        result[:company_size] = company_details['size']
        result[:type] = company_details['companyType']
        result[:industry] = company_details['industry']
        result[:founded] = company_details['yearFounded']
        headquarters = company_details['headquarters']
        if headquarters
          result[:address] = %{#{headquarters['street1']} #{headquarters['street2']} #{headquarters['city']}, #{headquarters['state']} #{headquarters['zip']} #{headquarters['country']}}
        end
        %i(street1 street2 city zip state country).each do |section|
          result[section] = headquarters[section.to_s]
        end
      end
      result
    end
```

**Comment by bricemaurin** [comment] 2016-05-11 07:27
thanks @yatish27
